using Invariable;
using System;
using System.Collections.Generic;
using System.IO;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEditor.Build;
using UnityEngine;



namespace MyTools
{
    public static class PreBuildValidator
    {
        public enum AppPackTarget
        {
            Android,
            iOS,
            OpenHarmony
        }

        private const string CloudServiceRelativeDir = "Assets/Scripts/CloudService";
        private const string CloudHelperRelativePath = "Assets/Scripts/CloudService/CloudHelper.cs";
        private const string PlayerSettingsRelativePath = "ProjectSettings/ProjectSettings.asset";
        private const string RemoteCallStubHeader = "// <auto-generated-by-uos>";
        private static readonly string[] SecretFieldNames =
        {
            "GameId"
        };



        /// <summary>
        /// 打包前校验，硬条件失败时返回 false
        /// </summary>
        public static bool ConfirmReadyToPack(AppPackTarget target)
        {
            try
            {
                List<string> issues = CollectIssues(target);

                if (issues.Count > 0)
                {
                    string detail = string.Join("；", issues);
                    GameLog.Error($"打包前检查未通过：{detail}");

                    return false;
                }

                WarnSigning(target);
                GameLog.Info("打包前检查通过。工程内无法验证 Func Stateless 是否已切远程调用，请自行确认远程模式后再出正式包");

                return true;
            }
            catch (Exception error)
            {
                string detail = $"检查脚本自身出错：{error.Message}";
                GameLog.Error($"打包前检查未通过：{detail}");

                return false;
            }
        }



        /// <summary>
        /// 收集 CDN、Secrets、BuildTarget、IL2CPP、ARM64、网络权限与包名问题
        /// </summary>
        private static List<string> CollectIssues(AppPackTarget target)
        {
            List<string> issues = new List<string>();

            if (target == AppPackTarget.Android && IsPlaceholder(InvariableConst.CDNPathAndroid))
            {
                issues.Add("CDNPathAndroid 为空或仍为占位符");
            }
            else if (target == AppPackTarget.iOS && IsPlaceholder(InvariableConst.CDNPathiOS))
            {
                issues.Add("CDNPathiOS 为空或仍为占位符");
            }
            else if (target == AppPackTarget.OpenHarmony && IsPlaceholder(InvariableConst.CDNPathOpenHarmony))
            {
                issues.Add("CDNPathOpenHarmony 为空或仍为占位符");
            }

            string helperText = ReadProjectText(CloudHelperRelativePath);

            if (helperText == null)
            {
                issues.Add("找不到 CloudHelper.cs，无法检查 Secrets");
            }
            else if (IsRemoteCallStub())
            {
                GameLog.Info("检测到远程调用桩，跳过 CloudHelper.Secrets 源码扫字段");
            }
            else
            {
                string secretsBlock = ReadSecretsInitializer(helperText);

                if (secretsBlock == null)
                {
                    issues.Add("找不到 CloudHelper.Secrets 初始化块");
                }
                else
                {
                    foreach (string fieldName in SecretFieldNames)
                    {
                        string value = ReadConstValue(secretsBlock, fieldName);

                        if (IsPlaceholder(value))
                        {
                            issues.Add($"CloudHelper.Secrets.{fieldName} 未填或仍为占位符");
                        }
                    }
                }
            }

            BuildTarget expectedTarget = GetBuildTarget(target);

            if (EditorUserBuildSettings.activeBuildTarget != expectedTarget)
            {
                issues.Add("当前 activeBuildTarget 与打包菜单不一致");
            }

            NamedBuildTarget namedTarget = GetNamedBuildTarget(target);

            if (PlayerSettings.GetScriptingBackend(namedTarget) != ScriptingImplementation.IL2CPP)
            {
                issues.Add("目标平台未使用 IL2CPP");
            }

            string appId = PlayerSettings.GetApplicationIdentifier(namedTarget);

            if (string.IsNullOrWhiteSpace(appId))
            {
                issues.Add("包名为空");
            }

            if (target == AppPackTarget.Android)
            {
                if ((PlayerSettings.Android.targetArchitectures & AndroidArchitecture.ARM64) == 0)
                {
                    issues.Add("安卓未包含 ARM64");
                }

                if (!PlayerSettings.Android.forceInternetPermission)
                {
                    issues.Add("安卓未强制网络权限");
                }
            }
            else if (target == AppPackTarget.OpenHarmony && !HasOpenHarmonyInternetPermission())
            {
                issues.Add("鸿蒙未强制网络权限");
            }

            return issues;
        }

        /// <summary>
        /// 签名证书只警告不硬拦
        /// </summary>
        private static void WarnSigning(AppPackTarget target)
        {
            if (target == AppPackTarget.Android && !PlayerSettings.Android.useCustomKeystore)
            {
                GameLog.Info("打包前检查：安卓未配置自定义 keystore，不阻断本次打包");
            }
            else if (target == AppPackTarget.iOS && string.IsNullOrEmpty(PlayerSettings.iOS.appleDeveloperTeamID))
            {
                GameLog.Info("打包前检查：苹果未配置 Team ID，不阻断本次打包");
            }
            else if (target == AppPackTarget.OpenHarmony)
            {
                GameLog.Info("打包前检查：鸿蒙证书与 Profile 需本机填写，不阻断本次打包");
            }
        }

        /// <summary>
        /// 打包菜单对应的 BuildTarget
        /// </summary>
        public static BuildTarget GetBuildTarget(AppPackTarget target)
        {
            if (target == AppPackTarget.Android)
            {
                return BuildTarget.Android;
            }

            if (target == AppPackTarget.iOS)
            {
                return BuildTarget.iOS;
            }

            return BuildTarget.OpenHarmony;
        }

        /// <summary>
        /// 打包菜单对应的 BuildTargetGroup
        /// </summary>
        public static BuildTargetGroup GetBuildTargetGroup(AppPackTarget target)
        {
            if (target == AppPackTarget.Android)
            {
                return BuildTargetGroup.Android;
            }

            if (target == AppPackTarget.iOS)
            {
                return BuildTargetGroup.iOS;
            }

            return BuildTargetGroup.OpenHarmony;
        }

        /// <summary>
        /// 打包菜单对应的 NamedBuildTarget
        /// </summary>
        private static NamedBuildTarget GetNamedBuildTarget(AppPackTarget target)
        {
            return NamedBuildTarget.FromBuildTargetGroup(GetBuildTargetGroup(target));
        }

        /// <summary>
        /// 读取工程设置中的鸿蒙网络权限开关
        /// </summary>
        private static bool HasOpenHarmonyInternetPermission()
        {
            string text = ReadProjectText(PlayerSettingsRelativePath);

            if (text == null)
            {
                return false;
            }

            return Regex.IsMatch(text, @"(?m)^\s*forceOpenHarmonyInternetPermission:\s*1\s*$");
        }

        /// <summary>
        /// 空值或 {占位符} 视为未配置
        /// </summary>
        private static bool IsPlaceholder(string value)
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                return true;
            }

            return Regex.IsMatch(value, @"\{[^}]+\}");
        }

        /// <summary>
        /// 按 UOS 规则判断云函数目录是否已切远程调用桩
        /// </summary>
        private static bool IsRemoteCallStub()
        {
            string projectRoot = Path.GetDirectoryName(Application.dataPath);
            string cloudDir = Path.Combine(projectRoot, CloudServiceRelativeDir);

            if (!Directory.Exists(cloudDir))
            {
                return false;
            }

            foreach (string filePath in Directory.GetFiles(cloudDir, "*.cs", SearchOption.AllDirectories))
            {
                using (StreamReader reader = new StreamReader(filePath))
                {
                    string firstLine = reader.ReadLine();

                    if (firstLine != null
                        && string.Equals(firstLine.Trim(), RemoteCallStubHeader, StringComparison.OrdinalIgnoreCase))
                    {
                        return true;
                    }
                }
            }

            return false;
        }

        /// <summary>
        /// 取出 Secrets 对象初始化块，找不到返回 null
        /// </summary>
        private static string ReadSecretsInitializer(string source)
        {
            if (string.IsNullOrEmpty(source))
            {
                return null;
            }

            Match match = Regex.Match(source, @"static\s+readonly\s+GameSecrets\s+Secrets\s*=\s*new\s+GameSecrets\s*\{(?<body>[\s\S]*?)\};");

            if (!match.Success)
            {
                return null;
            }

            return match.Groups["body"].Value;
        }

        /// <summary>
        /// 从源码读取 Name = "value" 的首个赋值，字段名按标识符边界匹配
        /// </summary>
        private static string ReadConstValue(string source, string name)
        {
            Match match = Regex.Match(source, @"(?<![A-Za-z0-9_])" + Regex.Escape(name) + @"(?![A-Za-z0-9_])\s*=\s*""([^""]*)""");

            if (match.Success)
            {
                return match.Groups[1].Value;
            }

            return null;
        }

        /// <summary>
        /// 按项目根相对路径读取文本，文件不存在返回 null
        /// </summary>
        private static string ReadProjectText(string relativePath)
        {
            string projectRoot = Path.GetDirectoryName(Application.dataPath);
            string fullPath = Path.Combine(projectRoot, relativePath);

            if (!File.Exists(fullPath))
            {
                return null;
            }

            return File.ReadAllText(fullPath);
        }
    }
}
