using System.IO;
using System.Text;



namespace MyTools
{
    public static class CodeGenerator
    {
        /// <summary>
        /// 生成 Config_X 与 ConfigManager 访问方法
        /// </summary>
        public static void Generate(AnalyzedTable table, string generatedDir)
        {
            Directory.CreateDirectory(generatedDir);
            var stringBuilder = new StringBuilder();
            string className = table.TableName;
            int schemaHash = ConfigSchemaHash.Compute(table);
            int slotCount = 0;

            for (int i = 0; i < table.Fields.Count; i++)
            {
                slotCount += table.Fields[i].WireSize / 4;
            }

            stringBuilder.AppendLine("// <auto-generated>");
            stringBuilder.AppendLine("// 本文件由 VastStarryRiver/Config/导出Excel配置 生成，请勿手改");
            stringBuilder.AppendLine("using Invariable;");
            stringBuilder.AppendLine("using System;");
            stringBuilder.AppendLine("using System.Collections.Generic;");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine();
            stringBuilder.AppendLine();
            stringBuilder.AppendLine("namespace HotUpdate");
            stringBuilder.AppendLine("{");
            stringBuilder.AppendLine($"    public sealed class Config_{className} : ConfigBase");
            stringBuilder.AppendLine("    {");
            stringBuilder.AppendLine($"        public const int SchemaHash = {schemaHash};");
            stringBuilder.AppendLine($"        private const int SlotCount = {slotCount};");
            stringBuilder.AppendLine($"        private readonly int[] Slots = new int[SlotCount];");
            stringBuilder.AppendLine();

            foreach (ConfigField field in table.Fields)
            {
                if (field.Name == "Id")
                {
                    continue;
                }

                string comment = string.IsNullOrEmpty(field.Comment) ? field.Name : field.Comment.Replace("\r", " ").Replace("\n", " ");
                stringBuilder.AppendLine($"        public {field.CsType} {field.Name}; // {comment}");
            }

            stringBuilder.AppendLine();
            stringBuilder.AppendLine();
            stringBuilder.AppendLine();
            stringBuilder.AppendLine("        public override void Deserialize(ConfigReader configReader)");
            stringBuilder.AppendLine("        {");
            stringBuilder.AppendLine("            configReader.ReadSlots(Slots, SlotCount);");
            stringBuilder.AppendLine("            int i = 0;");

            foreach (ConfigField field in table.Fields)
            {
                AppendDeserializeField(stringBuilder, field);
            }

            stringBuilder.AppendLine("        }");
            stringBuilder.AppendLine("    }");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine("    public static partial class ConfigManager");
            stringBuilder.AppendLine("    {");
            stringBuilder.AppendLine($"        private static ConfigManagerCore.ConfigData<Config_{className}> m_config{className} = null;");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine();
            stringBuilder.AppendLine();
            stringBuilder.AppendLine("        /// <summary>");
            stringBuilder.AppendLine($"        /// 按 Id 获取单条 {className} 配置");
            stringBuilder.AppendLine("        /// </summary>");
            stringBuilder.AppendLine($"        public static void Get{className}ByID(int id, Action<Config_{className}> callBack)");
            stringBuilder.AppendLine("        {");
            stringBuilder.AppendLine("            if (callBack == null)");
            stringBuilder.AppendLine("            {");
            stringBuilder.AppendLine("                return;");
            stringBuilder.AppendLine("            }");
            stringBuilder.AppendLine($"            Get{className}((dic) =>");
            stringBuilder.AppendLine("            {");
            stringBuilder.AppendLine("                if (dic == null)");
            stringBuilder.AppendLine("                {");
            stringBuilder.AppendLine("                    callBack(null);");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine("                    return;");
            stringBuilder.AppendLine("                }");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine($"                if (!dic.TryGetValue(id, out Config_{className} row))");
            stringBuilder.AppendLine("                {");
            stringBuilder.AppendLine($"                    GameLog.Error($\"Config_{className} 不存在 Id={{id}}\");");
            stringBuilder.AppendLine("                    callBack(null);");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine("                    return;");
            stringBuilder.AppendLine("                }");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine("                callBack(row);");
            stringBuilder.AppendLine("            });");
            stringBuilder.AppendLine("        }");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine("        /// <summary>");
            stringBuilder.AppendLine($"        /// 按 Id 列表获取多条 {className} 配置");
            stringBuilder.AppendLine("        /// </summary>");
            stringBuilder.AppendLine($"        public static void Get{className}ByIDs(int[] ids, Action<List<Config_{className}>> callBack)");
            stringBuilder.AppendLine("        {");
            stringBuilder.AppendLine("            if (callBack == null)");
            stringBuilder.AppendLine("            {");
            stringBuilder.AppendLine("                return;");
            stringBuilder.AppendLine("            }");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine("            if (ids == null)");
            stringBuilder.AppendLine("            {");
            stringBuilder.AppendLine("                callBack(null);");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine("                return;");
            stringBuilder.AppendLine("            }");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine($"            Get{className}((dic) =>");
            stringBuilder.AppendLine("            {");
            stringBuilder.AppendLine("                if (dic == null)");
            stringBuilder.AppendLine("                {");
            stringBuilder.AppendLine("                    callBack(null);");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine("                    return;");
            stringBuilder.AppendLine("                }");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine($"                var list = new List<Config_{className}>(ids.Length);");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine("                for (int i = 0; i < ids.Length; i++)");
            stringBuilder.AppendLine("                {");
            stringBuilder.AppendLine($"                    if (!dic.TryGetValue(ids[i], out Config_{className} row))");
            stringBuilder.AppendLine("                    {");
            stringBuilder.AppendLine($"                        GameLog.Error($\"Config_{className} 不存在 Id={{ids[i]}}\");");
            stringBuilder.AppendLine("                        callBack(null);");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine("                        return;");
            stringBuilder.AppendLine("                    }");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine("                    list.Add(row);");
            stringBuilder.AppendLine("                }");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine("                callBack(list);");
            stringBuilder.AppendLine("            });");
            stringBuilder.AppendLine("        }");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine("        /// <summary>");
            stringBuilder.AppendLine($"        /// 加载整张 {className} 配置表");
            stringBuilder.AppendLine("        /// </summary>");
            stringBuilder.AppendLine($"        public static void Get{className}(Action<DictionaryForConfig<Config_{className}>> callBack)");
            stringBuilder.AppendLine("        {");
            stringBuilder.AppendLine("            if (callBack == null)");
            stringBuilder.AppendLine("            {");
            stringBuilder.AppendLine("                return;");
            stringBuilder.AppendLine("            }");
            stringBuilder.AppendLine($"            LoadConfigData(ref m_config{className}, \"{className}\", Config_{className}.SchemaHash, (configData) =>");
            stringBuilder.AppendLine("            {");
            stringBuilder.AppendLine("                callBack(configData != null ? configData.DicData : null);");
            stringBuilder.AppendLine("            });");
            stringBuilder.AppendLine("        }");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine("        /// <summary>");
            stringBuilder.AppendLine($"        /// 分片加载全部 {className} 配置行");
            stringBuilder.AppendLine("        /// </summary>");
            stringBuilder.AppendLine($"        public static void GetAll{className}(Action<IReadOnlyList<Config_{className}>> onComplete, Action<int, int> onProgress = null)");
            stringBuilder.AppendLine("        {");
            stringBuilder.AppendLine("            if (onComplete == null)");
            stringBuilder.AppendLine("            {");
            stringBuilder.AppendLine("                return;");
            stringBuilder.AppendLine("            }");
            stringBuilder.AppendLine($"            LoadAllSliced(ref m_config{className}, \"{className}\", Config_{className}.SchemaHash, onComplete, onProgress);");
            stringBuilder.AppendLine("        }");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine("        /// <summary>");
            stringBuilder.AppendLine($"        /// 清除 {className} 配置缓存");
            stringBuilder.AppendLine("        /// </summary>");
            stringBuilder.AppendLine($"        public static void Clear{className}()");
            stringBuilder.AppendLine("        {");
            stringBuilder.AppendLine($"            ClearConfigData(ref m_config{className});");
            stringBuilder.AppendLine("        }");
            stringBuilder.AppendLine("    }");
            stringBuilder.Append("}");

            WriteAllTextLf(Path.Combine(generatedDir, $"Config_{className}.cs"), stringBuilder.ToString());
        }

        /// <summary>
        /// 生成 ConfigManager 预加载与 ClearAll
        /// </summary>
        public static void GeneratePreload(string[] tableNames, string generatedDir)
        {
            Directory.CreateDirectory(generatedDir);
            var stringBuilder = new StringBuilder();
            stringBuilder.AppendLine("// <auto-generated>");
            stringBuilder.AppendLine("// 本文件由 VastStarryRiver/Config/导出Excel配置 生成，请勿手改");
            stringBuilder.AppendLine("using Invariable;");
            stringBuilder.AppendLine("using System;");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine();
            stringBuilder.AppendLine();
            stringBuilder.AppendLine("namespace HotUpdate");
            stringBuilder.AppendLine("{");
            stringBuilder.AppendLine("    public static partial class ConfigManager");
            stringBuilder.AppendLine("    {");
            stringBuilder.AppendLine("        /// <summary>");
            stringBuilder.AppendLine("        /// 预加载全部配置表 bytes（可选，用于加载界面预热）");
            stringBuilder.AppendLine("        /// </summary>");
            stringBuilder.AppendLine("        public static void PreloadAll(Action callBack)");
            stringBuilder.AppendLine("        {");

            if (tableNames == null || tableNames.Length == 0)
            {
                stringBuilder.AppendLine("            callBack?.Invoke();");
            }
            else
            {
                stringBuilder.AppendLine($"            int remain = {tableNames.Length};");
                stringBuilder.AppendLine("            Action step = () =>");
                stringBuilder.AppendLine("            {");
                stringBuilder.AppendLine("                remain--;");
                stringBuilder.AppendLine("                if (remain <= 0)");
                stringBuilder.AppendLine("                {");
                stringBuilder.AppendLine("                    callBack?.Invoke();");
                stringBuilder.AppendLine("                }");
                stringBuilder.AppendLine("            };");

                foreach (string name in tableNames)
                {
                    stringBuilder.AppendLine($"            Get{name}((data) =>");
                    stringBuilder.AppendLine("            {");
                    stringBuilder.AppendLine("                if (data == null)");
                    stringBuilder.AppendLine("                {");
                    stringBuilder.AppendLine($"                    GameLog.Error(\"预加载配置失败：{name}\");");
                    stringBuilder.AppendLine("                }");
                    stringBuilder.AppendLine();
                    stringBuilder.AppendLine("                step();");
                    stringBuilder.AppendLine("            });");
                }
            }

            stringBuilder.AppendLine("        }");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine("        /// <summary>");
            stringBuilder.AppendLine("        /// 清除全部配置表缓存");
            stringBuilder.AppendLine("        /// </summary>");
            stringBuilder.AppendLine("        public static void ClearAll()");
            stringBuilder.AppendLine("        {");

            if (tableNames != null)
            {
                foreach (string name in tableNames)
                {
                    stringBuilder.AppendLine($"            Clear{name}();");
                }
            }

            stringBuilder.AppendLine("        }");
            stringBuilder.AppendLine("    }");
            stringBuilder.Append("}");

            WriteAllTextLf(Path.Combine(generatedDir, "ConfigManager.Preload.cs"), stringBuilder.ToString());
        }



        /// <summary>
        /// 追加字段反序列化语句
        /// </summary>
        private static void AppendDeserializeField(StringBuilder stringBuilder, ConfigField field)
        {
            if (field.ArrayLength > 0)
            {
                stringBuilder.AppendLine($"            {field.Name} = new {GetElementCsType(field.Primitive)}[{field.ArrayLength}];");

                for (int i = 0; i < field.ArrayLength; i++)
                {
                    stringBuilder.AppendLine($"            {field.Name}[{i}] = {SlotExpression(field.Primitive)};");
                }
            }
            else
            {
                stringBuilder.AppendLine($"            {field.Name} = {SlotExpression(field.Primitive)};");
            }
        }

        /// <summary>
        /// 获取数组元素的 C# 类型名
        /// </summary>
        private static string GetElementCsType(ConfigPrimitive primitive)
        {
            switch (primitive)
            {
                case ConfigPrimitive.Int:
                    return "int";

                case ConfigPrimitive.Float:
                    return "float";

                case ConfigPrimitive.String:
                    return "string";

                default:
                    return "int";
            }
        }

        /// <summary>
        /// 生成从 Slots 取值的表达式
        /// </summary>
        private static string SlotExpression(ConfigPrimitive primitive)
        {
            switch (primitive)
            {
                case ConfigPrimitive.Int:
                    return "Slots[i++]";

                case ConfigPrimitive.Float:
                    return "BitConverter.Int32BitsToSingle(Slots[i++])";

                case ConfigPrimitive.String:
                    return "configReader.ReadStringByOffset(Slots[i++])";

                default:
                    return "Slots[i++]";
            }
        }

        /// <summary>
        /// 以 UTF-8 无 BOM + LF 行尾写入文本文件
        /// </summary>
        private static void WriteAllTextLf(string path, string content)
        {
            content = content.Replace("\r\n", "\n").Replace("\r", "\n");
            File.WriteAllText(path, content, new UTF8Encoding(false));
        }
    }
}